// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgZBvyhGZ8xMzYoKWHgxmhPeRxv2_ISaw',
    appId: '1:616123701902:web:b0d27467b315e0af8547df',
    messagingSenderId: '616123701902',
    projectId: 'fir-link-a8266',
    authDomain: 'fir-link-a8266.firebaseapp.com',
    storageBucket: 'fir-link-a8266.firebasestorage.app',
    measurementId: 'G-8TSHG1SGRS',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgZBvyhGZ8xMzYoKWHgxmhPeRxv2_ISaw',
    appId: '1:616123701902:web:0041433e69e040b68547df',
    messagingSenderId: '616123701902',
    projectId: 'fir-link-a8266',
    authDomain: 'fir-link-a8266.firebaseapp.com',
    storageBucket: 'fir-link-a8266.firebasestorage.app',
    measurementId: 'G-8XP7Y72ZKB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTKSz3QtnGUVMgBM8VTtEgES1MpeVz74',
    appId: '1:616123701902:ios:31ec503c6869bb1f8547df',
    messagingSenderId: '616123701902',
    projectId: 'fir-link-a8266',
    storageBucket: 'fir-link-a8266.firebasestorage.app',
    iosBundleId: 'com.ex',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAByLdPSuMwH8bS2VjXfTPCtnp8EyE8EZ0',
    appId: '1:616123701902:android:374e2d644fcc31448547df',
    messagingSenderId: '616123701902',
    projectId: 'fir-link-a8266',
    storageBucket: 'fir-link-a8266.firebasestorage.app',
  );
}
